services:
  postgres:
    image: postgres:15
    container_name: postgresql-fastapi
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"

  fastapi-app:
    build:
      context: .
    container_name: fastapi-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      PYTHONUNBUFFERED: "1"
      MODE: development
      DATABASE_URL: postgresql://devuser:devpassword@postgres:5432/dev_db
